***Data loading***

In [11]:
from scipy.io import arff
import pandas as pd

In [12]:
from scipy.io import arff
import pandas as pd

# Replace 'your_file.arff' with the actual path to your ARFF file
file_path = 'data.arff'

# Load ARFF file
data, meta = arff.loadarff(file_path)

# Convert to pandas DataFrame and decode bytes to strings
df = pd.DataFrame(data)
df = df.applymap(lambda x: x.decode('utf-8') if isinstance(x, bytes) else x)

In [13]:
df

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,United States,no,6.0,18 and more,Self,NO
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5.0,18 and more,Self,NO
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8.0,18 and more,Parent,YES
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,United States,no,6.0,18 and more,Self,NO
4,1,0,0,0,0,0,0,1,0,0,...,f,?,no,no,Egypt,no,2.0,18 and more,?,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,f,White-European,no,no,Russia,no,7.0,18 and more,Self,YES
700,1,0,0,0,0,0,0,1,0,1,...,m,Hispanic,no,no,Mexico,no,3.0,18 and more,Parent,NO
701,1,0,1,1,1,0,1,1,0,1,...,f,?,no,no,Russia,no,7.0,18 and more,?,YES
702,1,0,0,1,1,0,1,0,1,1,...,m,South Asian,no,no,Pakistan,no,6.0,18 and more,Self,NO
703,1,0,1,1,1,0,1,1,1,1,...,f,White-European,no,no,Cyprus,no,8.0,18 and more,Self,YES

In [14]:
# Rename the "Class" column to "label"
df.rename(columns={'Class/ASD': 'label'}, inplace=True)

# Replace "NO" with 0 and "YES" with 1 in the "label" column
df['label'] = df['label'].replace({'NO': 0, 'YES': 1})

In [15]:
df

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,label
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,United States,no,6.0,18 and more,Self,0
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5.0,18 and more,Self,0
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8.0,18 and more,Parent,1
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,United States,no,6.0,18 and more,Self,0
4,1,0,0,0,0,0,0,1,0,0,...,f,?,no,no,Egypt,no,2.0,18 and more,?,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,f,White-European,no,no,Russia,no,7.0,18 and more,Self,1
700,1,0,0,0,0,0,0,1,0,1,...,m,Hispanic,no,no,Mexico,no,3.0,18 and more,Parent,0
701,1,0,1,1,1,0,1,1,0,1,...,f,?,no,no,Russia,no,7.0,18 and more,?,1
702,1,0,0,1,1,0,1,0,1,1,...,m,South Asian,no,no,Pakistan,no,6.0,18 and more,Self,0
703,1,0,1,1,1,0,1,1,1,1,...,f,White-European,no,no,Cyprus,no,8.0,18 and more,Self,1

***Data Pre-processing***

In [16]:
# Check for missing values or '?' symbols in all columns
for column in df.columns:
    missing_values = df[column].isin(['?', None]).sum()
    if missing_values > 0:
        print(f"Column '{column}' has {missing_values} missing values or '?' symbols.")

Column 'ethnicity' has 95 missing values or '?' symbols.
Column 'relation' has 95 missing values or '?' symbols.

In [17]:
# Check for missing values or '?' symbols in all columns
for column in df.columns:
    missing_values = df[column].isin(['?', None]).sum()
    nan_values = df[column].isnull().sum()
    
    if missing_values > 0 or nan_values > 0:
        print(f"Column '{column}' has {missing_values} missing values or '?' symbols and {nan_values} NaN values.")

Column 'age' has 0 missing values or '?' symbols and 2 NaN values.
Column 'ethnicity' has 95 missing values or '?' symbols and 0 NaN values.
Column 'relation' has 95 missing values or '?' symbols and 0 NaN values.

In [18]:
# Removed rows with ? and nan values
df_cleaned = df[~df.apply(lambda row: row.isin(['?', None]).any(), axis=1)].dropna()

In [19]:

df_cleaned

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,label
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,United States,no,6.0,18 and more,Self,0
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5.0,18 and more,Self,0
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8.0,18 and more,Parent,1
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,United States,no,6.0,18 and more,Self,0
5,1,1,1,1,1,0,1,1,1,1,...,m,Others,yes,no,United States,no,9.0,18 and more,Self,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698,1,1,1,1,1,1,1,1,1,1,...,f,Pasifika,no,no,Australia,no,10.0,18 and more,Self,1
699,0,1,0,1,1,0,1,1,1,1,...,f,White-European,no,no,Russia,no,7.0,18 and more,Self,1
700,1,0,0,0,0,0,0,1,0,1,...,m,Hispanic,no,no,Mexico,no,3.0,18 and more,Parent,0
702,1,0,0,1,1,0,1,0,1,1,...,m,South Asian,no,no,Pakistan,no,6.0,18 and more,Self,0
703,1,0,1,1,1,0,1,1,1,1,...,f,White-European,no,no,Cyprus,no,8.0,18 and more,Self,1

In [20]:
df_cleaned.to_csv('cleaned_data.csv',index=False)